# toml-docs-start lang-main
[en]
    languageName = "English"
    contentDir = "content"
    weight = 1
# toml-docs-end lang-main
# toml-docs-start lang-param
    [en.params.head]
        tagline = "The Soul of Ceylon Flavor"
    [en.params.social]
        title = "Stay tuned"
        caption = "Happy cooking with SÃ‰PICE ğŸ²"
    [en.params.footer]
# toml-docs-end lang-param
